export const MARKETPLACESOLUTIONSFILTERCONST: any =


[{"id":1,"parent_id":null,"filter_category":"Industry And Sector","level_value":1},
{"id":27,"parent_id":null,"filter_category":"Region","level_value":1},
{"id":32,"parent_id":null,"filter_category":"Processes","level_value":1},
{"id":33,"parent_id":32,"filter_category":"L1","level_value":2},
{"id":28,"parent_id":27,"filter_category":"GLOBAL","level_value":2},
{"id":29,"parent_id":27,"filter_category":"NA","level_value":2},
{"id":30,"parent_id":27,"filter_category":"LATAM","level_value":2},
{"id":31,"parent_id":27,"filter_category":"APAC","level_value":2},
{"id":2,"parent_id":1,"filter_category":"COMMON","level_value":2},
{"id":4,"parent_id":1,"filter_category":"CONSUMER","level_value":2},
{"id":7,"parent_id":1,"filter_category":"ENERGY, RESOURCES & INDUSTRIALS","level_value":2},
{"id":11,"parent_id":1,"filter_category":"FINANCIAL SERVICES","level_value":2},
{"id":14,"parent_id":1,"filter_category":"GOVERNMENT & PUBLIC SERVICES","level_value":2},
{"id":18,"parent_id":1,"filter_category":"LIFE SCIENCES & HEALTH CARE","level_value":2},
{"id":21,"parent_id":1,"filter_category":"TECHNOLOGY, MEDIA & TELECOM","level_value":2},
{"id":25,"parent_id":1,"filter_category":"OTHER","level_value":2},
{"id":26,"parent_id":25,"filter_category":"UNCLASSIFIED INDUSTRIES","level_value":3},
{"id":22,"parent_id":21,"filter_category":"TECHNOLOGY","level_value":3},
{"id":23,"parent_id":21,"filter_category":"TECHNOLOGY, MEDIA & TELECOM","level_value":3},
{"id":24,"parent_id":21,"filter_category":"TELECOM, MEDIA & ENTERTAINMENT","level_value":3},
{"id":19,"parent_id":18,"filter_category":"HEALTH CARE","level_value":3},
{"id":20,"parent_id":18,"filter_category":"LIFE SCIENCES","level_value":3},
{"id":15,"parent_id":14,"filter_category":"CIVIL GOVERNMENT","level_value":3},
{"id":16,"parent_id":14,"filter_category":"DEFENSE, SECURITY & JUSTICE","level_value":3},
{"id":17,"parent_id":14,"filter_category":"FEDERAL HEALTH","level_value":3},
{"id":12,"parent_id":11,"filter_category":"BANKING & CAPITAL MARKETS","level_value":3},
{"id":13,"parent_id":11,"filter_category":"HOLDING COMPANIES","level_value":3},
{"id":8,"parent_id":7,"filter_category":"INDUSTRIAL PRODUCTS & CONSTRUCTION","level_value":3},
{"id":9,"parent_id":7,"filter_category":"OIL, GAS & CHEMICALS","level_value":3},
{"id":10,"parent_id":7,"filter_category":"POWER & UTILITIES","level_value":3},
{"id":39,"parent_id":7,"filter_category":"COMMON","level_value":3},
{"id":5,"parent_id":4,"filter_category":"AUTOMOTIVE, TRANSPORTATION, HOSPITALITY","level_value":3},
{"id":6,"parent_id":4,"filter_category":"RETAIL & CONSUMER PRODUCTS","level_value":3},
{"id":3,"parent_id":2,"filter_category":"COMMON","level_value":3},
{"id":34,"parent_id":33,"filter_category":"1 RTR","level_value":3},
{"id":35,"parent_id":33,"filter_category":"2 PTP","level_value":3},
{"id":36,"parent_id":33,"filter_category":"3 OTC","level_value":3},
{"id":37,"parent_id":33,"filter_category":"4 PTM","level_value":3},
{"id":38,"parent_id":33,"filter_category":"5 PTC","level_value":3}];